version: "3.9"

services:

  postgres:
    image: postgres:14.2
    container_name: rails-auth-db
    environment:
      POSTGRES_DB: app_development
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: redis:7.0
    container_name: rails-auth-redis
    volumes:
      - ./data/redis:/var/lib/redis/data

  app:
    container_name: rails-auth-app
    build:
      context: .
    volumes:
      - ./src:/opt/app
    links:
      - postgres
      - redis
    ports:
      - '8010:8010'
    env_file:
      - .env

  sidekiq:
    container_name: rails-auth-sidekiq
    build:
      context: .
    command: bundle exec sidekiq 
    links:
      - postgres
      - redis
    env_file:
      - .env

  nginx:
    container_name: rails-auth-nginx
    build:
      context: .
      dockerfile: ./Dockerfile.nginx
    links:
      - app
    ports:
      - '8020:8020'